baseURL = "https://ishanjsr.github.io/"
languageCode = "en-us"
title = "Ishan Anand"
theme = "PaperMod"
paginate = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  title = "Ishan Anand"
  description = "Assistant Professor of Economics, IIT Delhi"
  author = "Ishan Anand"

  [params.profileMode]
    enabled = true
    title = "Ishan Anand"
    subtitle = "Assistant Professor of Economics | Department of Humanities & Social Sciences | IIT Delhi\n\nI am an Assistant Professor of Economics at IIT Delhi. I work on inequality, climate change, history of economic thought, and development. I am also into open water swimming."
    imageUrl = "images/profile.jpg"
    imageWidth = 220
    imageHeight = 220

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ianand@iitd.ac.in"

  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=t5YYVSUAAAAJ&hl=en"

  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 10

[[menu.main]]
  identifier = "PopularWri"
  name = "Popular-writings"
  url = "/Popular-writings/"
  weight = 30

[[menu.main]]
  identifier = "swim"
  name = "Swim Stuff"
  url = "/swim-stuff/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]